MyEvent/Models/EventHolder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyEvent.Models;

public partial class EventHolder
{
    public string EventHolderID { get; set; } = null!;

    [Display(Name = "主辦團體")]
    [Required(ErrorMessage = "此欄為必填")]
    public string EventHolderName { get; set; } = null!;

    [Display(Name = "加入日期")]
    public DateTime JoinDate { get; set; }

    [Display(Name = "電話")]
    [Required(ErrorMessage = "此欄為必填")]
    public string Tel { get; set; } = null!;

    [Display(Name = "郵遞區號")]
    [Required(ErrorMessage = "此欄為必填")]
    public string ZipCode { get; set; } = null!;

    [Display(Name = "城市")]
    [Required(ErrorMessage = "此欄為必填")]
    public string City { get; set; } = null!;

    [Display(Name = "區域")]
    [Required(ErrorMessage = "此欄為必填")]
    public string Area { get; set; } = null!;

    [Display(Name = "地址")]
    [Required(ErrorMessage = "此欄為必填")]
    public string Address { get; set; } = null!;

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();

    public virtual ECredentials? ECredentials { get; set; } = null!;
}

MyEvent/Controllers/EventHoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodStore.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyEvent.Models;
using Newtonsoft.Json;

namespace MyEvent.Controllers
{
    [ServiceFilter(typeof(AdminLoginFilter))]
    public class EventHoldersController : Controller
    {
        private readonly MyEventContext _context;

        public EventHoldersController(MyEventContext context)
        {
            _context = context;
        }

        // GET: EventHolders
        public async Task<IActionResult> Index()
        {
            return View(await _context.EventHolder.ToListAsync());
        }

        // GET: EventHolders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventHolder = await _context.EventHolder
                .FirstOrDefaultAsync(m => m.EventHolderID == id);
            if (eventHolder == null)
            {
                return NotFound();
            }

            return View(eventHolder);
        }

        // GET: EventHolders/Create
        public IActionResult Create()
        {
            callViewBagData();
            return View();
        }

        // POST: EventHolders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventHolder eventHolder)
        {
            callViewBagData();
            if (_context.ECredentials.Find(eventHolder.ECredentials.Account) != null)
            {
                ViewData["ErrorMessage"] = "帳號已存在";
                return View(eventHolder);
            }

            eventHolder.JoinDate = DateTime.Now;
            eventHolder.EventHolderID = Guid.NewGuid().ToString();
            ModelState.Remove("EventHolderID");

            if (ModelState.IsValid)
            {
                _context.Add(eventHolder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventHolder);
        }

        // GET: EventHolders/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventHolder = await _context.EventHolder.FindAsync(id);
            if (eventHolder == null)
            {
                return NotFound();
            }
            return View(eventHolder);
        }

        // POST: EventHolders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EventHolder eventHolder)
        {
            if (id != eventHolder.EventHolderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingEventHolder = await _context.EventHolder.FindAsync(id);
                    if (existingEventHolder == null)
                    {
                        return NotFound();
                    }

                    // 保持 JoinDate 不變
                    eventHolder.JoinDate = existingEventHolder.JoinDate;
                    existingEventHolder.EventHolderName = eventHolder.EventHolderName;
                    existingEventHolder.Tel = eventHolder.Tel;
                    existingEventHolder.ZipCode = eventHolder.ZipCode;
                    existingEventHolder.City = eventHolder.City;
                    existingEventHolder.Area = eventHolder.Area;
                    existingEventHolder.Address = eventHolder.Address;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventHolderExists(eventHolder.EventHolderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventHolder);
        }

        // GET: EventHolders/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventHolder = await _context.EventHolder
                .FirstOrDefaultAsync(m => m.EventHolderID == id);
            if (eventHolder == null)
            {
                return NotFound();
            }

            return View(eventHolder);
        }

        // POST: EventHolders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var eventHolder = await _context.EventHolder.FindAsync(id);
            if (eventHolder != null)
            {
                _context.EventHolder.Remove(eventHolder);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventHolderExists(string id)
        {
            return _context.EventHolder.Any(e => e.EventHolderID == id);
        }

        private void callViewBagData()
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "data", "area_data.json");
            var json = System.IO.File.ReadAllText(filePath);
            var areaData = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, AreaInfo>>>(json);

            ViewBag.AreaData = areaData;

            var cities = areaData.Keys.ToList();
            ViewBag.Cities = cities;

            var districts = areaData
            .SelectMany(city => city.Value.Keys)
            .ToList();

            ViewBag.Districts = districts;
        }
    }
}

MyEvent/Views/EventHolders/Create.cshtml
@using System.Text.Json;
@model MyEvent.Models.EventHolder

@{
    ViewData["Title"] = "Create";
    var areaData = ViewBag.AreaData as Dictionary<string, Dictionary<string, AreaInfo>>;
    var cities = ViewBag.Cities as List<string>;
    var districts = ViewBag.Districts as List<string>;
}

<h4 class="fw-bold text-center mt-4">新增主辦團體</h4>
<hr />
<div class="d-flex justify-content-center">
    <div class="row mx-auto" style="width:300px;">
        <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="text-danger">@ViewData["ErrorMessage"]</div>
            <div class="form-group">
                <label asp-for="ECredentials.Account" class="control-label"></label>
                <input asp-for="ECredentials.Account" class="form-control" />
                <span asp-validation-for="ECredentials.Account" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="ECredentials.Password" class="control-label"></label>
                <input asp-for="ECredentials.Password" type="password" class="form-control" />
                <span asp-validation-for="ECredentials.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventHolderName" class="control-label"></label>
                <input asp-for="EventHolderName" class="form-control" />
                <span asp-validation-for="EventHolderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select id="city" name="City" class="form-control" onchange="updateDistricts()">
                    @* <option value="-1" selected>請選擇城市</option>  *@
                    @foreach (var city in cities)
                    {

                        @if (Model?.City == city)
                        {
                            <option value="@city" selected>@city</option>
                        }
                        else
                        {
                            <option value="@city">@city</option>
                        }
                    }
                </select>
                <span asp-validation-for="City" class="text-danger"></span>
                @* <span class="text-danger">@ViewData["ErrorMessage"]</span> *@
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <select id="district" name="Area" class="form-control" disabled>
                    @* <option value="">請先選擇城市</option> *@
                </select>
                <span asp-validation-for="Area" class="text-danger"></span>
                @* <span class="text-danger">@ViewData["ErrorMessage"]</span> *@
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 align-items-center d-flex justify-content-center">
                <input type="submit" value="建立帳號" class="btn btn-secondary" />
                <a asp-action="Index" class="btn btn-outline-secondary ms-2">返回列表</a>
            </div>
        </form>
    </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        const areaData = @Html.Raw(JsonSerializer.Serialize(areaData));
        const selectedArea = "@(Model?.Area)";

            function updateDistricts() {
                const city = document.getElementById('city').value;
                const districtSelect = document.getElementById('district');

                // 清空區域選單
                districtSelect.innerHTML = '<option value="">請選擇區域</option>';

                if (city && areaData[city]) {
                    // 根據選擇的城市填充區域選單
                    for (const district in areaData[city]) {
                        const option = document.createElement('option');
                        option.value = district; // 區域名稱作為值
                        option.textContent = district; // 顯示區域名稱

                        if (district == selectedArea) {
                            option.selected = true;
                        }

                        districtSelect.appendChild(option);
                    }
                    districtSelect.disabled = false;
                } else {
                    districtSelect.disabled = true;
                }

                $(districtSelect).removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(districtSelect);
            }

            window.onload = function() {
                if (document.getElementById('city').value) {
                    updateDistricts();
                }
            }

    </script>
}

MyEvent/Views/EventHolders/Delete.cshtml
@model MyEvent.Models.EventHolder

@{
	ViewData["Title"] = "Delete";
}

<h4 class="fw-bold text-primary text-center mt-4">確定刪除此主辦團體?</h4>
<div>
	<hr />
	<div class="d-flex justify-content-center">
		<dl class="row mx-auto" style="width:300px;">
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.EventHolderName)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.EventHolderName)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.JoinDate)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.JoinDate)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.Tel)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.Tel)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.ZipCode)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.ZipCode)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.City)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.City)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.Area)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.Area)
			</dd>
			<dt class="col-xl-4">
				@Html.DisplayNameFor(model => model.Address)
			</dt>
			<dd class="col-xl-8">
				@Html.DisplayFor(model => model.Address)
			</dd>
		</dl>
	</div>
	<form asp-action="Delete" class="mt-3 align-items-center d-flex justify-content-center">
		<input type="hidden" asp-for="EventHolderID" />
		<input type="submit" value="確認刪除" class="btn btn-secondary" />
		<a asp-action="Index" class="btn btn-outline-secondary ms-2">返回列表</a>
	</form>
</div>

MyEvent/Views/EventHolders/Details.cshtml
@model MyEvent.Models.EventHolder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EventHolder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventHolderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventHolderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JoinDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EventHolderID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyEvent/Views/EventHolders/Edit.cshtml
@model MyEvent.Models.EventHolder

@{
	ViewData["Title"] = "Edit";
}

<h4 class="fw-bold text-center mt-4">編輯主辦團體</h4>
<hr />
<div class="d-flex justify-content-center">
	<div class="row mx-auto" style="width:300px;">
		<div class="col-md-12">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="EventHolderID" class="control-label"></label>
					<input asp-for="EventHolderID" class="form-control" readonly/>
					<span asp-validation-for="EventHolderID" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="EventHolderName" class="control-label"></label>
					<input asp-for="EventHolderName" class="form-control" />
					<span asp-validation-for="EventHolderName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Tel" class="control-label"></label>
					<input asp-for="Tel" class="form-control" />
					<span asp-validation-for="Tel" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="ZipCode" class="control-label"></label>
					<input asp-for="ZipCode" class="form-control" />
					<span asp-validation-for="ZipCode" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="City" class="control-label"></label>
					<input asp-for="City" class="form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Area" class="control-label"></label>
					<input asp-for="Area" class="form-control" />
					<span asp-validation-for="Area" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Address" class="control-label"></label>
					<input asp-for="Address" class="form-control" />
					<span asp-validation-for="Address" class="text-danger"></span>
				</div>
				<div class="form-group mt-3 align-items-center d-flex justify-content-center">
					<input type="submit" value="儲存" class="btn btn-secondary" />
					<a asp-action="Index" class="btn btn-outline-secondary ms-2">返回列表</a>
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

MyEvent/Views/EventHolders/Index.cshtml
@model IEnumerable<MyEvent.Models.EventHolder>

@{
    ViewData["Title"] = "主辦團體帳號管理";
}


<div class="d-flex justify-content-between align-items-center my-3"> 
    <h4 class="fw-bold">@ViewData["Title"]</h4>
    <a asp-action="Create" asp-controller="EventHolders" class="btn btn-outline-dark mt-3">新增主辦團體 &nbsp;<i class="bi bi-patch-plus"></i></a>
</div>
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventHolderName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JoinDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventHolderName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JoinDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EventHolderID"><i class="bi bi-pencil-fill text-success" data-bs-trigger="hover" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="編輯"></i></a> |
                <a asp-action="Delete" asp-route-id="@item.EventHolderID"><i class="bi bi-trash3-fill text-primary" data-bs-trigger="hover" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="刪除"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>