MyEvent/Controllers/ManageOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoodStore.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyEvent.Models;

namespace MyEvent.Controllers
{
    public class ManageOrdersController : Controller
    {
        private readonly MyEventContext _context;
        public ManageOrdersController(MyEventContext context)
        {
            _context = context;
        }

        [ServiceFilter(typeof(AdminLoginFilter))]
        // GET: ManageOrders
        public async Task<IActionResult> Index()
        {
            var myEventContext = await _context.Order.Include(o => o.Event).Include(o => o.Member).OrderByDescending(o => o.Date).ToListAsync();
            return View( myEventContext);
        }

        // GET: ManageOrders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Event)
                .Include(o => o.Member)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: ManageOrders/Create
        public IActionResult Create()
        {
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID");
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID");
            ViewData["PaymentID"] = new SelectList(_context.Payment, "PaymentID", "PaymentID");
            return View();
        }

        // POST: ManageOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Date,Qty,Status,Memo,EventID,MemberID,PaymentID,TotalPrice")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", order.EventID);
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID", order.MemberID);
            return View(order);
        }

        // GET: ManageOrders/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Event)
                .Include(o => o.Member)
                .Include(o => o.OrderDetail)
                .FirstOrDefaultAsync(o => o.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", order.EventID);
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberName", order.Member.MemberID);
            //ViewData["PaymentID"] = new SelectList(_context.Payment, "PaymentID", "PaymentID", order.PaymentID);
            return View(order);
        }

        // POST: ManageOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", order.EventID);
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberName", order.MemberID);
            //ViewData["PaymentID"] = new SelectList(_context.Payment, "PaymentID", "PaymentID", order.PaymentID);
            return View(order);
        }

        //[ServiceFilter(typeof(AdminLoginFilter))]
        // GET: ManageOrders/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Event)
                .Include(o => o.Member)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: ManageOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Order.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(string id)
        {
            return _context.Order.Any(e => e.OrderID == id);
        }
    }
}

MyEvent/Views/ManageOrders/Create.cshtml
@model MyEvent.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderID" class="control-label"></label>
                <input asp-for="OrderID" class="form-control" />
                <span asp-validation-for="OrderID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Memo" class="control-label"></label>
                <input asp-for="Memo" class="form-control" />
                <span asp-validation-for="Memo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventID" class="control-label"></label>
                <select asp-for="EventID" class ="form-control" asp-items="ViewBag.EventID"></select>
            </div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <select asp-for="MemberID" class ="form-control" asp-items="ViewBag.MemberID"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyEvent/Views/ManageOrders/Delete.cshtml
@model MyEvent.Models.Order

@{
	ViewData["Title"] = "Delete";
}

<h4 class="fw-bold text-primary text-center mt-4">確定刪除此訂單?</h4>
<div>
	<hr />
	<div class="d-flex justify-content-center">
		<dl class="row mx-auto" style="width:400px;">
			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.Event)
			</dt>
			<dd class="col-sm-8">
				@Html.DisplayFor(model => model.Event.EventID)
			</dd>
			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.Date)
			</dt>
			<dd class="col-sm-8">
				@Html.DisplayFor(model => model.Date)
			</dd>
			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.Qty)
			</dt>
			<dd class="col-sm-8">
				@Html.DisplayFor(model => model.Qty)
			</dd>
			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.TotalPrice)
			</dt>
			<dd class="col-sm-8">
				@(Convert.ToInt32(Model.TotalPrice))
			</dd>

			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.Member)
			</dt>
			<dd class="col-sm-8">
				@Html.DisplayFor(model => model.Member.MemberName)
			</dd>
			<dt class="col-sm-4">
				@Html.DisplayNameFor(model => model.Memo)
			</dt>
			<dd class="col-sm-8">
				@Html.DisplayFor(model => model.Memo)
			</dd>
		</dl>
	</div>
	<form asp-action="Delete" class="mt-3 align-items-center d-flex justify-content-center">
		<input type="hidden" asp-for="OrderID" />
		<input type="submit" value="確認刪除" class="btn btn-secondary"/>
		<a asp-action="Index" class="btn btn-outline-secondary ms-2">返回列表</a>
	</form>
</div>

MyEvent/Views/ManageOrders/Details.cshtml
@model MyEvent.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Memo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Memo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Event.EventID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member.MemberID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OrderID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyEvent/Views/ManageOrders/Edit.cshtml
@model MyEvent.Models.Order

@{
    ViewData["Title"] = "編輯訂單";
}

<h4 class="fw-bold text-center mt-4">@ViewData["Title"]</h4>
<hr />
<div class="d-flex justify-content-center">
    <div class="row mx-auto" style="width:400px;">
        <div class="col-md-12">
        <form asp-action="Edit">
                <input type="hidden" asp-for="EventID" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="OrderID" class="control-label"></label>
            <input asp-for="OrderID" class="form-control" readonly/>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qty" class="control-label"></label>
                <input asp-for="Qty" class="form-control" />
                <span asp-validation-for="Qty" class="text-danger"></span>
            </div>
@*             <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Memo" class="control-label"></label>
                <textarea asp-for="Memo" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Memo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Member.MemberName" class="control-label"></label>
                <select asp-for="MemberID" class="form-control" asp-items="@ViewBag.MemberID"></select>
                <span asp-validation-for="MemberID" class="text-danger"></span>
            </div>
@*          <div class="form-group">
                <label asp-for="PaymentID" class="control-label"></label>
                <select asp-for="PaymentID" class="form-control" asp-items="ViewBag.PaymentID"></select>
                <span asp-validation-for="PaymentID" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 align-items-center d-flex justify-content-center">
                <input type="submit" value="儲存" class="btn btn-secondary" />
                <a asp-action="CheckOrder" asp-controller="EHLogin" asp-route-id="@ViewBag.EventID" class="btn btn-outline-secondary ms-2">返回列表</a>
            </div>
        </form>
    </div>
</div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyEvent/Views/ManageOrders/Index.cshtml
@model IEnumerable<MyEvent.Models.Order>

@{
    ViewData["Title"] = "訂單列表";
}

<h4 class="fw-bold text-center mt-4">@ViewData["Title"]</h4>

<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event.EventName)
            </th>
            <th> 
                 @Html.DisplayNameFor(model => model.Qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Event.EventName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Member.MemberName)
                </td>
                <td>
                    <a asp-action="Delete" asp-controller="ManageOrders" asp-route-id="@item.OrderID"><i class="bi bi-trash3-fill text-primary" data-bs-trigger="hover" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="刪除"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>