MyEvent/Controllers/MemberLoginController.cs
using GoodStore.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using MyEvent.Models;
using MyEvent.ViewModels;
using System.Text.Json;


namespace MyEvent.Controllers
{
    public class MemberLoginController : Controller
    {
        private readonly MyEventContext _context;

        public MemberLoginController(MyEventContext context)
        {
            _context = context;
        }

        [ServiceFilter(typeof(MemberLoginFilter))]
        public async Task<IActionResult> Index()
        {
            var id = HttpContext.Session.GetString("MemberID");

            var member = await _context.Member.Include(m => m.MemberTel).Include(m => m.CreditCard).Include(m => m.Credentials).Include(o=>o.Order).Where(o => o.MemberID == id).FirstOrDefaultAsync();
            var orders = await _context.Order.Where(o => o.MemberID == id).Include(o => o.Event).OrderByDescending(o => o.Date).ToListAsync();
            

            var orderDetails = await _context.OrderDetail
                .Where(od => od.Order.MemberID == id)
                .Include(od => od.TicketTypeList)
                .Include(od => od.Seat)
                .Include(od => od.Order)  // 關聯 Order 資料
                .ThenInclude(o => o.Event)
                .Select(od => new
                {
                    EventName = od.Order.Event.EventName,
                    EventTime = od.Order.Event.StartTime,
                    EventDate = od.Order.Event.Date,
                    EventPic = od.Order.Event.Pic,
                    Seat = $"{od.Seat.Row}-{od.Seat.Number}",
                    TicketID = od.TicketID,
                    TicketType = od.TicketTypeList.Name,
                    Price = od.Price
                })
                .OrderBy(od => od.EventDate)
                .ToListAsync();

            ViewBag.OrderDetails = orderDetails;
            ViewBag.Orders = orders;

            if (TempData.ContainsKey("OrderMessage"))
            {
                ViewBag.OrderMessage = TempData["OrderMessage"];
            }
            return View(member);
        }

        public IActionResult Create()
        {
            callViewBagData();

            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Member member)
        {
            callViewBagData();

            if (_context.Credentials.Find(member.Credentials.Account) != null)
            {
                ViewData["ErrorMessage"] = "帳號已存在";
                return View(member);
            }

            member.JoinDate = DateTime.Now;
            member.Role = "1";
            var memberID = DateTime.Now.ToString("yyyyMM");
            var currentYear = DateTime.Now.Year;
            var currentMonth = DateTime.Now.Month;

            var lastMember = _context.Member.Where(m => m.JoinDate.Year == currentYear && m.JoinDate.Month == currentMonth).OrderByDescending(m => m.MemberID).FirstOrDefault();
            var newMemberID = lastMember != null ? (int.Parse(lastMember.MemberID) + 1).ToString() : DateTime.Now.ToString("yyyyMM") + "0001";
            member.MemberID = newMemberID;
            ModelState.Remove("MemberID");
            ModelState.Remove("Role");

            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();

                HttpContext.Session.SetString("MemberID", member.MemberID);                
                string? eventId = HttpContext.Session.GetString("EventID");
                if (eventId != null)
                {
                    //瀏覽的演出
                    return RedirectToAction("Details", "Browse", new { id = eventId });
                }
                return RedirectToAction("Index", "Browse"); 
                ;

            }

            //要寫City跟Area跟角色 (如果沒有value)顯示errormessage


            return View(member);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(Credentials login)
        {
            var result = await _context.Credentials.Where(m => m.Account == login.Account && m.Password == login.Password).Include(m => m.Member).FirstOrDefaultAsync();


            if (result != null)
            {
                HttpContext.Session.SetString("MemberID", result.Member.MemberID);
                HttpContext.Session.SetString("Role", result.Member.Role);
                string? eventId = HttpContext.Session.GetString("EventID");
                string? role = HttpContext.Session.GetString("Role");
                if(role == "2")
                {
                    return RedirectToAction("Index", "Members");
                }
                if (eventId != null)
                {
                    //瀏覽的演出
                    return RedirectToAction("Details", "Browse", new { id = eventId });
                }
                return RedirectToAction("Index", "Browse");
                ;
            }
            else
            {
                ViewData["Message"] = "帳號或密碼錯誤";
            }
            return View(login);
        }

        public IActionResult Logout()
        {
            //5.4.2
            //HttpContext.Session.Clear():清除所有session
            HttpContext.Session.Remove("MemberID");
            HttpContext.Session.Remove("Role");

            return RedirectToAction("Index", "Home");
        }
        public bool MemberAccountCheck(string account)
        {
            var result = _context.Credentials.Where(m => m.Account == account).FirstOrDefault();

            return result == null;
            //帳號不重複回傳true
        }

        private void callViewBagData()
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "data", "area_data.json");
            var json = System.IO.File.ReadAllText(filePath);
            var areaData = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, AreaInfo>>>(json);

            ViewBag.AreaData = areaData;

            var cities = areaData.Keys.ToList();
            ViewBag.Cities = cities;

            var districts = areaData
            .SelectMany(city => city.Value.Keys)
            .ToList();

            ViewBag.Districts = districts;
            
        }

    }
}

MyEvent/Views/MemberLogin/Create.cshtml
@using System.Text.Json;
@model MyEvent.Models.Member;

@{

	ViewData["Title"] = "Create";
	var areaData = ViewBag.AreaData as Dictionary<string, Dictionary<string, AreaInfo>>;
	var cities = ViewBag.Cities as List<string>;
	var districts = ViewBag.Districts as List<string>;
	Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MyEvent</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MyEvent.styles.css" asp-append-version="true" />
</head>
<style>
	.backToBrowse {
		color: #5c5c5c;
		text-decoration: #5c5c5c solid 2px underline;
	}
	.backToBrowse:hover {
		color: #323232;
		text-decoration: #323232 solid 2px underline;
	}
	.btn-success {
		background-color: #099;
		border-color: #099;
	}
	.btn-success:hover {
		background-color: #098d8d;
		border-color: #098d8d;
	}
</style>
<body class="container">
	<h1 class="text-center mt-4">註冊帳號</h1>

	<div class="row d-flex justify-content-center">
		<div class="col-xl-4 col-md-6">
			<hr style="color:#099;" />
			<form asp-action="Create" method="post">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Credentials.Account" class="control-label"></label>
					<input asp-for="Credentials.Account" id="Account" class="form-control" />
					<span asp-validation-for="Credentials.Account" class="text-danger"></span>
					<span class="text-danger" id="AccountCheck"></span>
				</div>
				<div class="form-group">
					<label asp-for="Credentials.Password" class="control-label"></label>
					<input asp-for="Credentials.Password" type="password" class="form-control" />
					<span asp-validation-for="Credentials.Password" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="MemberName" class="control-label"></label>
					<input asp-for="MemberName" class="form-control" />
					<span asp-validation-for="MemberName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Birthday" class="control-label"></label>
					<input asp-for="Birthday" class="form-control" type="date" />
					<span asp-validation-for="Birthday" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="ZipCode" class="control-label"></label>
					<input asp-for="ZipCode" class="form-control" />
					<span asp-validation-for="ZipCode" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="City" class="control-label"></label>
					<select id="city" name="City" class="form-control" onchange="updateDistricts()">
						@* <option value="-1" selected>請選擇城市</option>  *@
						@foreach (var city in cities)
						{

							@if (Model?.City == city)
							{
								<option value="@city" selected>@city</option>
							}
							else
							{
								<option value="@city">@city</option>
							}
						}
					</select>
					<span asp-validation-for="City" class="text-danger"></span>
					@* <span class="text-danger">@ViewData["ErrorMessage"]</span> *@
				</div>
				<div class="form-group">
					<label asp-for="Area" class="control-label"></label>
					<select id="district" name="Area" class="form-control" disabled>
						@* <option value="">請先選擇城市</option> *@
					</select>
					<span asp-validation-for="Area" class="text-danger"></span>
					@* <span class="text-danger">@ViewData["ErrorMessage"]</span> *@
				</div>
				<div class="form-group">
					<label asp-for="Address" class="control-label"></label>
					<input asp-for="Address" class="form-control" />
					<span asp-validation-for="Address" class="text-danger"></span>
				</div>
				<div class="form-group mt-3 d-flex justify-content-center">
					<input type="submit" value="註冊" class="btn btn-success w-25"/>
				</div>
				<div class="d-flex justify-content-center mt-2">
					<a asp-action="Login" class="backToBrowse me-3">我要登入</a>
					<a asp-action="Index" asp-controller="Browse" class="backToBrowse">返回瀏覽</a>
				</div>
			</form>
		</div>
	</div>
	
</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script>
		const areaData = @Html.Raw(JsonSerializer.Serialize(areaData));
		const selectedArea = "@(Model?.Area)";

			function updateDistricts() {
				const city = document.getElementById('city').value;
				const districtSelect = document.getElementById('district');

				// 清空區域選單
				districtSelect.innerHTML = '<option value="">請選擇區域</option>';

				if (city && areaData[city]) {
					// 根據選擇的城市填充區域選單
					for (const district in areaData[city]) {
						const option = document.createElement('option');
						option.value = district; // 區域名稱作為值
						option.textContent = district; // 顯示區域名稱

						if (district == selectedArea) {
							option.selected = true;
						}

						districtSelect.appendChild(option);
					}
					districtSelect.disabled = false;
				} else {
					districtSelect.disabled = true;
				}

				$(districtSelect).removeData("unobtrusiveValidation");
				$.validator.unobtrusive.parse(districtSelect);
			}

			window.onload = function() {
				if (document.getElementById('city').value) {
					updateDistricts();
				}
			}
		
	</script>

MyEvent/Views/MemberLogin/Index.cshtml
@model MyEvent.Models.Member
@{
    ViewData["Title"] = "Login Index";
    int tc = 1;
    var role = ViewContext.HttpContext.Session.GetString("Role");
}
<style>
    .nav-item a {
        color: black;
    }
    .nav-item a:hover, .nav-link.active {
        color:var(--bs-success);
    }

    .name{
        background-color: rgba(0,153,153,.25);
        padding-top:40px;
        padding-bottom: 40px;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }
    .col-3{
        border-radius: 10px;
        height: 445px
    }
    .col-8 {
        border-radius: 10px;
    }

    .text-bg-dark {
        background-color: white;
        width: 450px;
        height: 50px;
        font-size: 1.2rem;
    }
    .card {
        border-radius: 1rem !important; 
        overflow: hidden;
    }

    .toast{
        height:70px;
    }
</style>

<div class="container row g-0 mt-5">
    <div class="col-3 shadow me-3">
        <div class="name text-center">
            <h5>嗨！@(Model.MemberName)</h5>
        </div>
        <ul class="nav flex-column" role="tablist">
            <li class="nav-item mt-3" role="presentation">
                <a class="nav-link active" id="order-tab" data-bs-toggle="tab" data-bs-target="#order-tab-pane" type="button" role="tab" aria-controls="order-tab-pane" aria-selected="true"><i class="bi bi-journal-text"></i>&nbsp; 訂購紀錄</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="ticket-tab" data-bs-toggle="tab" data-bs-target="#ticket-tab-pane" type="button" role="tab" aria-controls="ticket-tab-pane" aria-selected="true"><i class="bi bi-ticket-perforated"></i>&nbsp; 票匣</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="info-tab" data-bs-toggle="tab" data-bs-target="#info-tab-pane" type="button" role="tab" aria-controls="info-tab-pane" aria-selected="false"><i class="bi bi-person"></i>&nbsp; 基本資料</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="creditcard-tab" data-bs-toggle="tab" data-bs-target="#creditcard-tab-pane" type="button" role="tab" aria-controls="creditcard-tab-pane" aria-selected="false"><i class="bi bi-credit-card"></i>&nbsp; 信用卡</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="creditentials-tab" data-bs-toggle="tab" data-bs-target="#creditentials-tab-pane" type="button" role="tab" aria-controls="creditentials-tab-pane" aria-selected="false"><i class="bi bi-key"></i></i>&nbsp; 修改帳密</a>
            </li>
            <li class="text-center mt-5 mb-2">
                <a asp-action="Logout" asp-controller="MemberLogin" type="button" class="btn btn-outline-success w-75">登出</a>
            </li>
        </ul>
    </div>
    <div class="tab-content col-8 shadow p-4" id="myTabContent">
        <div class="tab-pane fade show active" id="order-tab-pane" role="tabpanel" aria-labelledby="order-tab" tabindex="0">
            <h5 class="text-success fw-bold">訂購紀錄</h5>
            @foreach (var order in ViewBag.Orders)
            {
                <div class="card mt-3">
                    <div class="card-header">
                        <p class="fw-bold my-auto">訂單編號：@order.OrderID</p>
                    </div>
                    <div class="card-body">
                        <p>訂購日期：@order.Date.ToString("yyyy-MM-dd")</p>
                        <p>演出名稱：@order.Event.EventName</p>
                    </div>
                    <div class="card-footer" style="background-color: white;">
                        <span>總票數：<span class="text-success fw-bold">@order.Qty</span></span>
                        <span class="ms-3">總金額：<span class="text-success fw-bold">$@Convert.ToInt32(order.TotalPrice)</span></span>
                    </div>
                </div>
            }
        </div>
        <div class="tab-pane fade" id="ticket-tab-pane" role="tabpanel" aria-labelledby="ticket-tab" tabindex="0">
            <h5 class="text-success fw-bold">票匣</h5>
            @foreach (var detail in ViewBag.OrderDetails)
            {
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-3 card-header py-3 d-flex justify-content-center" style="border-right: 2px dashed #ccc;">
                            <img src="~/EventPhotos/@detail.EventPic" class="card-img-top" style="height: 200px; width:150px; object-fit: cover; object-position: center;" />
                        </div>
                        <div class="col-md-9">
                            <div class="card-body">
                                <div><span class="fw-bold text-success">@detail.EventDate.ToString("yyyy-MM-dd")</span><span class="fw-bold text-success ms-1"> @detail.EventTime</span></div>
                                <p class="fw-bold">@detail.EventName</p>
                                <hr />
                                @if (@detail.Seat != "-")
                                {
                                    <p>座位：@detail.Seat</p>
                                }
                                else
                                {
                                    <p>座位：自由入座</p>
                                }
                                <p>票種：@detail.TicketType</p>
                                <p>票價：$@Convert.ToInt32(detail.Price)</p>
                                @* <p>票ID：@detail.TicketID</p> *@                           
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="tab-pane fade" id="info-tab-pane" role="tabpanel" aria-labelledby="info-tab" tabindex="0">
            <h5 class="text-success fw-bold">基本資料</h5>
            <hr class="w-100 my-3" />
            <p>生日：@Model.Birthday</p>
            @foreach (var mt in Model.MemberTel)
            {
                <p>電話@(tc)：@mt.Tel</p>
                tc++;
            }
            <p>地址：@Model.ZipCode@Model.City@Model.Area@Model.Address</p>
            <p>加入日期：@Model.JoinDate</p>
        </div>
        <div class="tab-pane fade" id="creditcard-tab-pane" role="tabpanel" aria-labelledby="creditcard-tab" tabindex="0">
            <h5 class="text-success fw-bold">信用卡</h5>
            @foreach (var cc in Model.CreditCard)
            {
            <div class="card mt-3">
                <div class="card-body">
                    <p>卡號：@cc.CardNo</p>
                    <p>安全碼：@cc.SecurityNo</p>
                </div>
            </div>
            }

        </div>
        <div class="tab-pane fade" id="creditentials-tab-pane" role="tabpanel" aria-labelledby="creditentials-tab" tabindex="0">
            <h5 class="text-success fw-bold">修改帳密</h5>
            <hr class="w-100 my-3" />
            <p>帳號：@Model.Credentials.Account</p>
            <p>密碼：@Model.Credentials.Password</p>
            <button class="btn btn-success my-auto" style="height:40px">修改</button>
        </div>
    </div>
</div>

<div class="toast-container position-fixed top-0 start-50 translate-middle-x p-4">
    <div id="addToast" class="toast text-bg-dark border-0 d-flex align-items-center justify-content-center d-none" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay='3000'>
        <div class="text-center">
            <div class="toast-body d-inline-block fs-5 fw-bold">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
@if (ViewBag.OrderMessage == "OK")
        {
        <script>
            const addToast = document.getElementById('addToast')
            addToast.classList.remove('d-none');
            const toastBootstrap = bootstrap.Toast.getOrCreateInstance(addToast)
            $('#addToast .toast-body').html('<i class="bi bi-patch-check-fill text-primary"></i>&nbsp; 【訂購成功】');
            toastBootstrap.show()
        </script>
         }
}

MyEvent/Views/MemberLogin/Login.cshtml
@model MyEvent.Models.Credentials

@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyEvent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyEvent.styles.css" asp-append-version="true" />
</head>
<style>
    .backToBrowse{
        color: #5c5c5c;
        text-decoration: #5c5c5c solid 2px underline;
    }
    .backToBrowse:hover{
        color: #323232;
        text-decoration: #323232 solid 2px underline;
    }   
</style>
<body class="container">

<h1 class="text-center mt-4">登入/註冊</h1>
    <div class="row d-flex justify-content-center">
        <div class="col-xl-4 col-md-6">
         <hr style="color:#099;"/>
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Account" class="control-label"></label>
                <input asp-for="Account" class="form-control" />
                <span asp-validation-for="Account" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password"  class="text-danger"></span>
            </div>
            <div class="text-danger">
                @ViewData["Message"]
            </div>
            <div class="form-group mt-3 d-flex justify-content-center">
                <input type="submit" value="登入" class="btn btn-success me-2" />
                <a asp-action="Create" asp-controller="MemberLogin" class="btn btn-success">註冊</a>
            </div>
            <div class="mt-3 d-flex justify-content-center">
                <a asp-action="Index" asp-controller="Browse" class="backToBrowse">下次再說，返回瀏覽</a>
            </div>
        </form>
    </a>
</div>
</body>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}